import type { StrategyActivityTopRecentFocusActionsLineageSectionProps } from './strategyActivityTopRecentFocusActionsTypes'

export type StrategyActivityTopRecentFocusActionsLineageBacktestSectionProps = Pick<
  StrategyActivityTopRecentFocusActionsLineageSectionProps,
  | 'activityLatestBacktest'
  | 'activityLatestBacktestStrategyId'
  | 'activityLatestBacktestReview'
  | 'activityLatestActionableBacktestRecord'
  | 'activityLatestActionableBacktestHasRecommendation'
  | 'activityLatestActionableBacktestDiffersFromLatest'
  | 'activityLatestActionableBacktestJobCanRetry'
  | 'activityLatestBacktestSourceChangeRequestId'
  | 'activityLatestBacktestSourceBacktestId'
  | 'activityLatestBacktestSourceReviewId'
  | 'activityLatestBacktestSourceProposalId'
  | 'latestBacktestReviewOpenId'
  | 'latestBacktestJobOpenId'
  | 'latestActionableBacktestJobOpenId'
  | 'serviceAvailable'
  | 'backtestMutationPending'
  | 'retryAgentJobMutationPending'
  | 'onOpenStrategyProposal'
  | 'onOpenChangeRequest'
  | 'onOpenBacktestDetail'
  | 'onOpenSourceReview'
  | 'onOpenReviewInspector'
  | 'onOpenAiSchedulerJob'
  | 'onRetryAgentJobWithFocus'
  | 'onRerunBacktestFromRecommendation'
>

export type StrategyActivityTopRecentFocusActionsLineagePrimaryReviewSectionProps = Pick<
  StrategyActivityTopRecentFocusActionsLineageSectionProps,
  | 'activityLatestActionablePrimaryReviewStrategyId'
  | 'activityLatestActionablePrimaryReviewHasRecommendation'
  | 'activityLatestActionablePrimaryReviewRecord'
  | 'activityLatestActionablePrimaryReviewDiffersFromLatest'
  | 'latestActionablePrimaryReviewOpenId'
  | 'latestPrimaryReviewSourceJobId'
  | 'latestPrimaryReviewSourceChangeRequestId'
  | 'latestPrimaryReviewSourceBacktestId'
  | 'latestPrimaryReviewSourceReviewId'
  | 'latestPrimaryReviewSourceProposalId'
  | 'serviceAvailable'
  | 'backtestMutationPending'
  | 'onOpenStrategyProposal'
  | 'onOpenChangeRequest'
  | 'onOpenBacktestDetail'
  | 'onOpenSourceReview'
  | 'onOpenAiSchedulerJob'
  | 'onRerunBacktestFromReview'
>

export type StrategyActivityTopRecentFocusActionsLineageTrackingSectionProps = Pick<
  StrategyActivityTopRecentFocusActionsLineageSectionProps,
  | 'activityLatestTrackingJobLinkedReviewId'
  | 'activityLatestTrackingJobChangeRequestId'
  | 'activityLatestTrackingJobBacktestId'
  | 'activityLatestTrackingJobSourceChangeRequestId'
  | 'activityLatestTrackingJobSourceBacktestId'
  | 'activityLatestTrackingJobSourceReviewId'
  | 'activityLatestTrackingJobSourceProposalId'
  | 'activityLatestTrackingJobStrategyId'
  | 'latestTrackingReviewSourceJobId'
  | 'latestTrackingReviewSourceChangeRequestId'
  | 'latestTrackingReviewSourceBacktestId'
  | 'latestTrackingReviewSourceReviewId'
  | 'latestTrackingReviewSourceProposalId'
  | 'onOpenStrategyProposal'
  | 'onOpenChangeRequest'
  | 'onOpenBacktestDetail'
  | 'onOpenSourceReview'
  | 'onOpenAiSchedulerJob'
  | 'onOpenReviewInspector'
>
