import type { StrategyActivityTopRecentFocusActionsProps } from './strategyActivityTopRecentFocusActionsTypes'
import StrategyActivityTopRecentFocusActionsLineageSection from './StrategyActivityTopRecentFocusActionsLineageSection'
import StrategyActivityTopRecentFocusActionsRecentSection from './StrategyActivityTopRecentFocusActionsRecentSection'

export default function TopRecentFocusActions({
  showLatestFocusActions,
  showLineageActions,
  strategyId,
  activityLatestProposal,
  activityLatestChangeRequest,
  activityLatestChangeRequestStrategyId,
  activityLatestBacktest,
  activityLatestPrimaryReviewStrategyId,
  activityLatestTrackingReviewStrategyId,
  activityLatestBacktestStrategyId,
  activityLatestBacktestReview,
  activityLatestActionableBacktestRecord,
  activityLatestActionableBacktestHasRecommendation,
  activityLatestActionableBacktestDiffersFromLatest,
  activityLatestActionableBacktestJobCanRetry,
  activityLatestBacktestSourceChangeRequestId,
  activityLatestBacktestSourceBacktestId,
  activityLatestBacktestSourceReviewId,
  activityLatestBacktestSourceProposalId,
  activityLatestActionablePrimaryReviewStrategyId,
  activityLatestActionablePrimaryReviewHasRecommendation,
  activityLatestActionablePrimaryReviewRecord,
  activityLatestActionablePrimaryReviewDiffersFromLatest,
  activityLatestTrackingJobLinkedReviewId,
  activityLatestTrackingJobChangeRequestId,
  activityLatestTrackingJobBacktestId,
  activityLatestTrackingJobSourceChangeRequestId,
  activityLatestTrackingJobSourceBacktestId,
  activityLatestTrackingJobSourceReviewId,
  activityLatestTrackingJobSourceProposalId,
  activityLatestTrackingJobStrategyId,
  latestPrimaryReviewOpenId,
  latestTrackingReviewOpenId,
  latestTrackingJobOpenId,
  latestBacktestReviewOpenId,
  latestBacktestJobOpenId,
  latestActionableBacktestJobOpenId,
  latestActionablePrimaryReviewOpenId,
  latestPrimaryReviewSourceJobId,
  latestPrimaryReviewSourceChangeRequestId,
  latestPrimaryReviewSourceBacktestId,
  latestPrimaryReviewSourceReviewId,
  latestPrimaryReviewSourceProposalId,
  latestTrackingReviewSourceJobId,
  latestTrackingReviewSourceChangeRequestId,
  latestTrackingReviewSourceBacktestId,
  latestTrackingReviewSourceReviewId,
  latestTrackingReviewSourceProposalId,
  serviceAvailable,
  backtestMutationPending,
  retryAgentJobMutationPending,
  onOpenStrategyProposal,
  onOpenChangeRequest,
  onOpenBacktestDetail,
  onOpenReplayReview,
  onOpenReviewInspector,
  onOpenSourceReview,
  onOpenAiSchedulerJob,
  onRetryAgentJobWithFocus,
  onRerunBacktestFromRecommendation,
  onRerunBacktestFromReview,
}: StrategyActivityTopRecentFocusActionsProps) {
  return (
    <>
      <StrategyActivityTopRecentFocusActionsRecentSection
        showLatestFocusActions={showLatestFocusActions}
        strategyId={strategyId}
        activityLatestProposal={activityLatestProposal}
        activityLatestChangeRequest={activityLatestChangeRequest}
        activityLatestChangeRequestStrategyId={activityLatestChangeRequestStrategyId}
        activityLatestBacktest={activityLatestBacktest}
        activityLatestPrimaryReviewStrategyId={activityLatestPrimaryReviewStrategyId}
        activityLatestTrackingReviewStrategyId={activityLatestTrackingReviewStrategyId}
        latestPrimaryReviewOpenId={latestPrimaryReviewOpenId}
        latestTrackingReviewOpenId={latestTrackingReviewOpenId}
        latestTrackingJobOpenId={latestTrackingJobOpenId}
        onOpenStrategyProposal={onOpenStrategyProposal}
        onOpenChangeRequest={onOpenChangeRequest}
        onOpenBacktestDetail={onOpenBacktestDetail}
        onOpenReplayReview={onOpenReplayReview}
        onOpenReviewInspector={onOpenReviewInspector}
        onOpenAiSchedulerJob={onOpenAiSchedulerJob}
      />

      <StrategyActivityTopRecentFocusActionsLineageSection
        showLineageActions={showLineageActions}
        activityLatestBacktest={activityLatestBacktest}
        activityLatestBacktestStrategyId={activityLatestBacktestStrategyId}
        activityLatestBacktestReview={activityLatestBacktestReview}
        activityLatestActionableBacktestRecord={activityLatestActionableBacktestRecord}
        activityLatestActionableBacktestHasRecommendation={activityLatestActionableBacktestHasRecommendation}
        activityLatestActionableBacktestDiffersFromLatest={activityLatestActionableBacktestDiffersFromLatest}
        activityLatestActionableBacktestJobCanRetry={activityLatestActionableBacktestJobCanRetry}
        activityLatestBacktestSourceChangeRequestId={activityLatestBacktestSourceChangeRequestId}
        activityLatestBacktestSourceBacktestId={activityLatestBacktestSourceBacktestId}
        activityLatestBacktestSourceReviewId={activityLatestBacktestSourceReviewId}
        activityLatestBacktestSourceProposalId={activityLatestBacktestSourceProposalId}
        activityLatestActionablePrimaryReviewStrategyId={activityLatestActionablePrimaryReviewStrategyId}
        activityLatestActionablePrimaryReviewHasRecommendation={activityLatestActionablePrimaryReviewHasRecommendation}
        activityLatestActionablePrimaryReviewRecord={activityLatestActionablePrimaryReviewRecord}
        activityLatestActionablePrimaryReviewDiffersFromLatest={activityLatestActionablePrimaryReviewDiffersFromLatest}
        activityLatestTrackingJobLinkedReviewId={activityLatestTrackingJobLinkedReviewId}
        activityLatestTrackingJobChangeRequestId={activityLatestTrackingJobChangeRequestId}
        activityLatestTrackingJobBacktestId={activityLatestTrackingJobBacktestId}
        activityLatestTrackingJobSourceChangeRequestId={activityLatestTrackingJobSourceChangeRequestId}
        activityLatestTrackingJobSourceBacktestId={activityLatestTrackingJobSourceBacktestId}
        activityLatestTrackingJobSourceReviewId={activityLatestTrackingJobSourceReviewId}
        activityLatestTrackingJobSourceProposalId={activityLatestTrackingJobSourceProposalId}
        activityLatestTrackingJobStrategyId={activityLatestTrackingJobStrategyId}
        latestBacktestReviewOpenId={latestBacktestReviewOpenId}
        latestBacktestJobOpenId={latestBacktestJobOpenId}
        latestActionableBacktestJobOpenId={latestActionableBacktestJobOpenId}
        latestActionablePrimaryReviewOpenId={latestActionablePrimaryReviewOpenId}
        latestPrimaryReviewSourceJobId={latestPrimaryReviewSourceJobId}
        latestPrimaryReviewSourceChangeRequestId={latestPrimaryReviewSourceChangeRequestId}
        latestPrimaryReviewSourceBacktestId={latestPrimaryReviewSourceBacktestId}
        latestPrimaryReviewSourceReviewId={latestPrimaryReviewSourceReviewId}
        latestPrimaryReviewSourceProposalId={latestPrimaryReviewSourceProposalId}
        latestTrackingReviewSourceJobId={latestTrackingReviewSourceJobId}
        latestTrackingReviewSourceChangeRequestId={latestTrackingReviewSourceChangeRequestId}
        latestTrackingReviewSourceBacktestId={latestTrackingReviewSourceBacktestId}
        latestTrackingReviewSourceReviewId={latestTrackingReviewSourceReviewId}
        latestTrackingReviewSourceProposalId={latestTrackingReviewSourceProposalId}
        serviceAvailable={serviceAvailable}
        backtestMutationPending={backtestMutationPending}
        retryAgentJobMutationPending={retryAgentJobMutationPending}
        onOpenStrategyProposal={onOpenStrategyProposal}
        onOpenChangeRequest={onOpenChangeRequest}
        onOpenBacktestDetail={onOpenBacktestDetail}
        onOpenSourceReview={onOpenSourceReview}
        onOpenAiSchedulerJob={onOpenAiSchedulerJob}
        onRetryAgentJobWithFocus={onRetryAgentJobWithFocus}
        onRerunBacktestFromRecommendation={onRerunBacktestFromRecommendation}
        onRerunBacktestFromReview={onRerunBacktestFromReview}
      />
    </>
  )
}
