import type { TopActionableDecisionActionsProps } from './strategy-activity-sections/TopActionableDecisionActions'
import type { StrategyActivityTopRecentFocusActionsProps } from './strategy-activity-sections/strategyActivityTopRecentFocusActionsTypes'
import type { StrategyActivityTopDecisionActionsSectionModel } from './buildStrategyActivityTopDecisionActionsSectionModel'
import type { StrategyActivityTopDecisionActionsSectionProps } from './StrategyActivityTopDecisionActionsSection.types'
import type { StrategyActivityTopDecisionActionsSectionState } from './buildStrategyActivityTopDecisionActionsSectionState'

export function buildStrategyActivityTopDecisionActionsSectionAssembler(
  props: StrategyActivityTopDecisionActionsSectionProps,
  state: StrategyActivityTopDecisionActionsSectionState,
): StrategyActivityTopDecisionActionsSectionModel {
  return {
    latestProposalChangeSummaryText: props.latestProposalChangeSummaryText,
    topRecentFocusActionsProps: {
      showLatestFocusActions: state.showLatestFocusActions,
      showLineageActions: state.showLineageActions,
      strategyId: props.strategyId,
      activityLatestProposal: props.activityLatestProposal,
      activityLatestChangeRequest: props.activityLatestChangeRequest,
      activityLatestChangeRequestStrategyId: props.activityLatestChangeRequestStrategyId,
      activityLatestBacktest: props.activityLatestBacktest,
      activityLatestPrimaryReviewStrategyId: props.activityLatestPrimaryReviewStrategyId,
      activityLatestTrackingReviewStrategyId: props.activityLatestTrackingReviewStrategyId,
      activityLatestBacktestStrategyId: props.activityLatestBacktestStrategyId,
      activityLatestBacktestReview: props.activityLatestBacktestReview,
      activityLatestActionableBacktestRecord: props.activityLatestActionableBacktestRecord,
      activityLatestActionableBacktestHasRecommendation: props.activityLatestActionableBacktestHasRecommendation,
      activityLatestActionableBacktestDiffersFromLatest: props.activityLatestActionableBacktestDiffersFromLatest,
      activityLatestActionableBacktestJobCanRetry: props.activityLatestActionableBacktestJobCanRetry,
      activityLatestBacktestSourceChangeRequestId: props.activityLatestBacktestSourceChangeRequestId,
      activityLatestBacktestSourceBacktestId: props.activityLatestBacktestSourceBacktestId,
      activityLatestBacktestSourceReviewId: props.activityLatestBacktestSourceReviewId,
      activityLatestBacktestSourceProposalId: props.activityLatestBacktestSourceProposalId,
      activityLatestActionablePrimaryReviewStrategyId: props.activityLatestActionablePrimaryReviewStrategyId,
      activityLatestActionablePrimaryReviewHasRecommendation:
        props.activityLatestActionablePrimaryReviewHasRecommendation,
      activityLatestActionablePrimaryReviewRecord: props.activityLatestActionablePrimaryReviewRecord,
      activityLatestActionablePrimaryReviewDiffersFromLatest:
        props.activityLatestActionablePrimaryReviewDiffersFromLatest,
      activityLatestTrackingJobLinkedReviewId: props.activityLatestTrackingJobLinkedReviewId,
      activityLatestTrackingJobChangeRequestId: props.activityLatestTrackingJobChangeRequestId,
      activityLatestTrackingJobBacktestId: props.activityLatestTrackingJobBacktestId,
      activityLatestTrackingJobSourceChangeRequestId: props.activityLatestTrackingJobSourceChangeRequestId,
      activityLatestTrackingJobSourceBacktestId: props.activityLatestTrackingJobSourceBacktestId,
      activityLatestTrackingJobSourceReviewId: props.activityLatestTrackingJobSourceReviewId,
      activityLatestTrackingJobSourceProposalId: props.activityLatestTrackingJobSourceProposalId,
      activityLatestTrackingJobStrategyId: props.activityLatestTrackingJobStrategyId,
      latestPrimaryReviewOpenId: state.latestPrimaryReviewOpenId,
      latestTrackingReviewOpenId: state.latestTrackingReviewOpenId,
      latestTrackingJobOpenId: state.latestTrackingJobOpenId,
      latestBacktestReviewOpenId: state.latestBacktestReviewOpenId,
      latestBacktestJobOpenId: state.latestBacktestJobOpenId,
      latestActionableBacktestJobOpenId: state.latestActionableBacktestJobOpenId,
      latestActionablePrimaryReviewOpenId: state.latestActionablePrimaryReviewOpenId,
      latestPrimaryReviewSourceJobId: state.latestPrimaryReviewSourceJobId,
      latestPrimaryReviewSourceChangeRequestId: state.latestPrimaryReviewSourceChangeRequestId,
      latestPrimaryReviewSourceBacktestId: state.latestPrimaryReviewSourceBacktestId,
      latestPrimaryReviewSourceReviewId: state.latestPrimaryReviewSourceReviewId,
      latestPrimaryReviewSourceProposalId: state.latestPrimaryReviewSourceProposalId,
      latestTrackingReviewSourceJobId: state.latestTrackingReviewSourceJobId,
      latestTrackingReviewSourceChangeRequestId: state.latestTrackingReviewSourceChangeRequestId,
      latestTrackingReviewSourceBacktestId: state.latestTrackingReviewSourceBacktestId,
      latestTrackingReviewSourceReviewId: state.latestTrackingReviewSourceReviewId,
      latestTrackingReviewSourceProposalId: state.latestTrackingReviewSourceProposalId,
      serviceAvailable: props.serviceAvailable,
      backtestMutationPending: props.backtestMutationPending,
      retryAgentJobMutationPending: props.retryAgentJobMutationPending,
      onOpenStrategyProposal: props.onOpenStrategyProposal,
      onOpenChangeRequest: props.onOpenChangeRequest,
      onOpenBacktestDetail: props.onOpenBacktestDetail,
      onOpenReplayReview: props.onOpenReplayReview,
      onOpenReviewInspector: props.onOpenReviewInspector,
      onOpenSourceReview: props.onOpenSourceReview,
      onOpenAiSchedulerJob: props.onOpenAiSchedulerJob,
      onRetryAgentJobWithFocus: props.onRetryAgentJobWithFocus,
      onRerunBacktestFromRecommendation: props.onRerunBacktestFromRecommendation,
      onRerunBacktestFromReview: props.onRerunBacktestFromReview,
    } as StrategyActivityTopRecentFocusActionsProps,
    topActionableDecisionActionsProps: {
      showProposalChangeActions: state.showProposalChangeActions,
      showActionableActions: state.showActionableActions,
      activityLatestChangeRequest: props.activityLatestChangeRequest,
      activityLatestChangeRequestStrategyId: props.activityLatestChangeRequestStrategyId,
      activityLatestChangeRequestLinkedBacktestId: props.activityLatestChangeRequestLinkedBacktestId,
      activityLatestChangeRequestLinkedReviewId: props.activityLatestChangeRequestLinkedReviewId,
      activityLatestChangeRequestSourceBacktestId: props.activityLatestChangeRequestSourceBacktestId,
      activityLatestChangeRequestSourceBacktestStrategyId: props.activityLatestChangeRequestSourceBacktestStrategyId,
      activityLatestChangeRequestSourceReviewId: props.activityLatestChangeRequestSourceReviewId,
      activityLatestChangeRequestSourceReviewStrategyId: props.activityLatestChangeRequestSourceReviewStrategyId,
      activityLatestChangeRequestSourceProposalId: props.activityLatestChangeRequestSourceProposalId,
      activityLatestChangeRequestSourceProposalStrategyId: props.activityLatestChangeRequestSourceProposalStrategyId,
      activityLatestProposalLinkedChangeRequest: props.activityLatestProposalLinkedChangeRequest,
      activityLatestProposalLinkedBacktest: props.activityLatestProposalLinkedBacktest,
      activityLatestProposalLinkedReview: props.activityLatestProposalLinkedReview,
      activityLatestActionableProposal: props.activityLatestActionableProposal,
      activityLatestActionableProposalDiffersFromLatest: props.activityLatestActionableProposalDiffersFromLatest,
      activityLatestActionableProposalAcceptTitle: props.activityLatestActionableProposalAcceptTitle,
      activityLatestActionableProposalAcceptDisabled: props.activityLatestActionableProposalAcceptDisabled,
      activityLatestActionableChangeRequest: props.activityLatestActionableChangeRequest,
      activityLatestActionableChangeRequestDiffersFromLatest:
        props.activityLatestActionableChangeRequestDiffersFromLatest,
      activityLatestActionableChangeRequestHasRerunRecommendation:
        props.activityLatestActionableChangeRequestHasRerunRecommendation,
      activityLatestRetryableTrackingJob: props.activityLatestRetryableTrackingJob,
      activityLatestRetryableTrackingJobDiffersFromLatest: props.activityLatestRetryableTrackingJobDiffersFromLatest,
      latestProposalChangeRequestStrategyId: state.latestProposalChangeRequestStrategyId,
      latestProposalReviewStrategyId: state.latestProposalReviewStrategyId,
      latestProposalJobId: state.latestProposalJobId,
      latestChangeRequestJobId: state.latestChangeRequestJobId,
      actionableChangeRequestRetryJobId: state.actionableChangeRequestRetryJobId,
      actionableChangeRequestCanRetry: state.actionableChangeRequestCanRetry,
      retryableTrackingJobOpenId: state.retryableTrackingJobOpenId,
      serviceAvailable: props.serviceAvailable,
      proposalMutationPending: props.proposalMutationPending,
      backtestMutationPending: props.backtestMutationPending,
      retryAgentJobMutationPending: props.retryAgentJobMutationPending,
      onOpenStrategyProposal: props.onOpenStrategyProposal,
      onOpenChangeRequest: props.onOpenChangeRequest,
      onOpenBacktestDetail: props.onOpenBacktestDetail,
      onOpenReplayReview: props.onOpenReplayReview,
      onOpenReviewInspector: props.onOpenReviewInspector,
      onOpenSourceReview: props.onOpenSourceReview,
      onOpenAiSchedulerJob: props.onOpenAiSchedulerJob,
      onHandleProposalAction: props.onHandleProposalAction,
      onRetryAgentJobWithFocus: props.onRetryAgentJobWithFocus,
      onRerunBacktestFromChangeRequest: props.onRerunBacktestFromChangeRequest,
    } as TopActionableDecisionActionsProps,
  }
}
