import type { useAppWorkspaceBootstrapState } from './useAppWorkspaceBootstrapState'
import type { useControlDataQueryModel } from './useControlDataQueryModel'
import type { useWorkspaceDraftModel } from './useWorkspaceDraftModel'

type BuildWorkspaceDraftModelArgs = Parameters<typeof useWorkspaceDraftModel>[0]
type AppWorkspaceBootstrapState = ReturnType<typeof useAppWorkspaceBootstrapState>
type ControlDataQueryModel = ReturnType<typeof useControlDataQueryModel>

export type BuildWorkspaceDraftModelArgsInput =
  AppWorkspaceBootstrapState &
  ControlDataQueryModel

export function buildWorkspaceDraftModelArgs({
  activeSection,
  layoutPreset,
  selectedMode,
  selectedSymbol,
  selectedMarketTimeframe,
  selectedStrategy,
  selectedStrategyId,
  selectedBacktestId,
  aiSchedulerFocusedJobId,
  strategyActivityPanelOpen,
  strategyTrackingPanelOpen,
  strategyEditorOpen,
  strategyTrackingKind,
  strategyTrackingSummary,
  strategyTrackingDetail,
  strategyEditorDraftStrategyId,
  parameterDrafts,
  riskBudgetDraft,
  reviewInspectorOpen,
  reviewInspectorReviewId,
  reviewInspectorStrategyId,
  replayFocusedReviewId,
  selectedProposalId,
  selectedChangeRequestId,
  backtestFilter,
  replayTrackingScope,
  alertSeverityFilter,
  alertStatusFilter,
  alertScopeFilter,
  tradeModeFilter,
  tradeOriginFilter,
  tradeScopeFilter,
  auditSeverityFilter,
  auditSourceFilter,
  auditScopeFilter,
  auditSearch,
  cardOrder,
  visibleOverviewCards,
  collapsedOverviewCards,
}: BuildWorkspaceDraftModelArgsInput): BuildWorkspaceDraftModelArgs {
  return {
    activeSection,
    layoutPreset,
    selectedMode,
    selectedSymbol,
    selectedMarketTimeframe,
    selectedStrategy,
    selectedStrategyId,
    selectedBacktestId,
    aiSchedulerFocusedJobId,
    strategyActivityPanelOpen,
    strategyTrackingPanelOpen,
    strategyEditorOpen,
    strategyTrackingKind,
    strategyTrackingSummary,
    strategyTrackingDetail,
    strategyEditorDraftStrategyId,
    parameterDrafts,
    riskBudgetDraft,
    reviewInspectorOpen,
    reviewInspectorReviewId,
    reviewInspectorStrategyId,
    replayFocusedReviewId,
    selectedProposalId,
    selectedChangeRequestId,
    backtestFilter,
    replayTrackingScope,
    alertSeverityFilter,
    alertStatusFilter,
    alertScopeFilter,
    tradeModeFilter,
    tradeOriginFilter,
    tradeScopeFilter,
    auditSeverityFilter,
    auditSourceFilter,
    auditScopeFilter,
    auditSearch,
    cardOrder,
    visibleOverviewCards,
    collapsedOverviewCards,
  }
}
