import type { StrategyActivityDecisionSectionsProps, StrategyActivityDecisionSectionsViewProps } from './StrategyActivityDecisionSections.types'
import { getChangeRequestStrategyId } from '../utils/app-helpers'

export function buildStrategyActivityDecisionSectionsViewProps({
  strategyId,
  recentProposalIds,
  recentChangeRequestIds,
  recentBacktestIds,
  selectedStrategyProposal,
  selectedStrategyChangeRequest,
  selectedProposalId,
  selectedChangeRequestId,
  selectedBacktest,
  strategyActivityLatestProposalSupplemented,
  strategyActivityLatestActionableProposalSupplemented,
  strategyActivityLatestChangeRequestSupplemented,
  strategyActivityLatestActionableChangeRequestSupplemented,
  strategyActivityLatestBacktestSupplemented,
  strategyActivityLatestActionableBacktestSupplemented,
  strategyActivityProposals,
  strategyActivityChangeRequests,
  strategyActivityBacktests,
  activityLatestProposal,
  activityLatestActionableProposal,
  activityLatestChangeRequest,
  activityLatestActionableChangeRequest,
  activityLatestBacktest,
  activityLatestActionableBacktest,
  activityLatestActionableBacktestReview,
  activityLatestBacktestReview,
  activityLatestActionableBacktestJob,
  activityLatestBacktestJob,
  backtests,
  reviewCatalog,
  backtestReviewJobs,
  serviceAvailable,
  proposalMutationPending,
  backtestMutationPending,
  retryAgentJobMutationPending,
  getStrategyActivityProposalLinkedState,
  getStrategyActivityChangeRequestLinkedState,
  proposalFocusLabels,
  getProposalBlockedReason,
  backtestFocusLabels,
  onOpenStrategyProposal,
  onOpenChangeRequest,
  onOpenBacktestDetail,
  onOpenReviewInspector,
  onOpenReplayReview,
  onOpenAiSchedulerJob,
  onOpenSourceReview,
  onRetryAgentJob,
  onHandleProposalAction,
  onRerunBacktestFromChangeRequest,
}: StrategyActivityDecisionSectionsProps): StrategyActivityDecisionSectionsViewProps {
  const focusedProposalSupplemented = Boolean(
    selectedStrategyProposal &&
      selectedStrategyProposal.strategy_id === strategyId &&
      !recentProposalIds.includes(selectedStrategyProposal.id),
  )
  const focusedChangeRequestSupplemented = Boolean(
    selectedStrategyChangeRequest &&
      getChangeRequestStrategyId(selectedStrategyChangeRequest, strategyId) === strategyId &&
      !recentChangeRequestIds.includes(selectedStrategyChangeRequest.id),
  )
  const focusedBacktestSupplemented = Boolean(
    selectedBacktest &&
      selectedBacktest.strategy_id === strategyId &&
      !recentBacktestIds.includes(selectedBacktest.id),
  )

  return {
    proposalListProps: {
      focusedProposalSupplemented,
      strategyActivityLatestProposalSupplemented,
      strategyActivityLatestActionableProposalSupplemented,
      strategyActivityProposals,
      activityLatestProposal,
      activityLatestActionableProposal,
      selectedProposalId,
      serviceAvailable,
      proposalMutationPending,
      retryAgentJobMutationPending,
      getStrategyActivityProposalLinkedState,
      proposalFocusLabels,
      getProposalBlockedReason,
      onOpenStrategyProposal,
      onOpenChangeRequest,
      onOpenBacktestDetail,
      onOpenReplayReview,
      onOpenReviewInspector,
      onOpenAiSchedulerJob,
      onRetryAgentJob,
      onHandleProposalAction,
    },
    changeRequestListProps: {
      strategyId,
      focusedChangeRequestSupplemented,
      strategyActivityLatestChangeRequestSupplemented,
      strategyActivityLatestActionableChangeRequestSupplemented,
      strategyActivityChangeRequests,
      activityLatestChangeRequest,
      activityLatestActionableChangeRequest,
      selectedChangeRequestId,
      serviceAvailable,
      backtestMutationPending,
      retryAgentJobMutationPending,
      getStrategyActivityChangeRequestLinkedState,
      onOpenChangeRequest,
      onOpenBacktestDetail,
      onOpenReviewInspector,
      onOpenAiSchedulerJob,
      onOpenSourceReview,
      onOpenStrategyProposal,
      onRetryAgentJob,
      onRerunBacktestFromChangeRequest,
    },
    backtestListProps: {
      strategyId,
      focusedBacktestSupplemented,
      strategyActivityLatestBacktestSupplemented,
      strategyActivityLatestActionableBacktestSupplemented,
      strategyActivityBacktests,
      activityLatestBacktest,
      activityLatestActionableBacktest,
      activityLatestActionableBacktestReview,
      activityLatestBacktestReview,
      activityLatestActionableBacktestJob,
      activityLatestBacktestJob,
      backtests,
      reviewCatalog,
      backtestReviewJobs,
      serviceAvailable,
      retryAgentJobMutationPending,
      backtestFocusLabels,
      onOpenBacktestDetail,
      onOpenReviewInspector,
      onOpenAiSchedulerJob,
      onOpenChangeRequest,
      onOpenSourceReview,
      onOpenStrategyProposal,
      onRetryAgentJob,
    },
  }
}
