import type { BuildAppSurfaceModelsArgsInput } from './buildAppSurfaceModelsArgs'
import type {
  BuildAppOverlayPanelsSurfaceDataArgsInput,
  BuildAppOverlayPanelsSurfacePendingArgsInput,
} from './buildAppOverlayPanelsSurfaceDataArgs'

type AppOverlayPanelsSurfaceArgs = BuildAppSurfaceModelsArgsInput['appOverlayPanels']

export type BuildAppOverlayPanelsSurfaceRuntimeArgsInput =
  BuildAppOverlayPanelsSurfaceDataArgsInput & BuildAppOverlayPanelsSurfacePendingArgsInput

export function buildAppOverlayPanelsSurfaceRuntimeArgs({
  snapshotScheduler,
  serviceAvailable,
  settings,
  grafanaStatus,
  metricsPreviewLines,
  pendingAlertsCount,
  selectedMode,
  selectedSymbol,
  editingOrder,
  manualOrder,
  manualTradePreviewLoading,
  manualTradePreview,
  manualTradingBlockedReason,
  watchlist,
  watchlistDraftSymbol,
  watchlistDraftMarket,
  watchlistAlertDrafts,
  accountOverview,
  bybitPrivateStatus,
  bybitPublicStatus,
  tradeProbeResult,
  tradeProbePending,
  parameterDrafts,
  riskBudgetDraft,
  hasParameterDraftChanges,
  parameterDraftPatchCount,
  riskBudgetChanged,
  selectedStrategy,
  strategyTrackingKind,
  strategyTrackingSummary,
  strategyTrackingDetail,
  reviewInspectorReviewId,
  reviewInspectorStrategyId,
  tradeOriginFilter,
  tradeScopeFilter,
  filteredOrderHistory,
  changeRequestMutationPending,
  schedulerMutationPending,
  watchlistAddPending,
  watchlistRemovePending,
  manualTradeMutationPending,
  exchangeOrderMutationPending,
  paperOrderMutationPending,
  replacePaperOrderPending,
  replaceExchangeOrderPending,
  cancelPaperOrderPending,
  cancelExchangeOrderPending,
  strategyTrackingMutationPending,
  backtestMutationPending,
  retryAgentJobMutationPending,
  proposalMutationPending,
}: BuildAppOverlayPanelsSurfaceRuntimeArgsInput): Pick<
  AppOverlayPanelsSurfaceArgs,
  'dataState' | 'pendingState'
> {
  return {
    dataState: {
      snapshotScheduler,
      serviceAvailable,
      settings,
      grafanaStatus,
      metricsPreviewLines,
      pendingAlertsCount,
      selectedMode,
      selectedSymbol,
      editingOrder,
      manualOrder,
      manualTradePreviewLoading,
      manualTradePreview,
      manualTradingBlockedReason,
      watchlist,
      watchlistDraftSymbol,
      watchlistDraftMarket,
      watchlistAlertDrafts,
      accountOverview,
      bybitPrivateStatus,
      bybitPublicStatus,
      tradeProbeResult,
      tradeProbePending,
      parameterDrafts,
      riskBudgetDraft,
      hasParameterDraftChanges,
      parameterDraftPatchCount,
      riskBudgetChanged,
      selectedStrategy,
      strategyTrackingKind,
      strategyTrackingSummary,
      strategyTrackingDetail,
      reviewInspectorReviewId,
      reviewInspectorStrategyId,
      tradeOriginFilter,
      tradeScopeFilter,
      filteredOrderHistory,
    },
    pendingState: {
      changeRequestMutationPending,
      schedulerMutationPending,
      watchlistAddPending,
      watchlistRemovePending,
      manualTradeMutationPending,
      exchangeOrderMutationPending,
      paperOrderMutationPending,
      replacePaperOrderPending,
      replaceExchangeOrderPending,
      cancelPaperOrderPending,
      cancelExchangeOrderPending,
      strategyTrackingMutationPending,
      backtestMutationPending,
      retryAgentJobMutationPending,
      proposalMutationPending,
    },
  }
}
