import { buildStrategyActivityOpsSectionProps } from './buildStrategyActivityOpsSectionProps'
import type { BuildStrategyActivityFloatingPanelSectionPropsArgs } from './buildStrategyActivityFloatingPanelSectionProps'

export function buildStrategyActivityFloatingPanelOpsSectionProps({
  derivedState,
  collectionState,
  serviceState,
  actions,
}: BuildStrategyActivityFloatingPanelSectionPropsArgs) {
  return buildStrategyActivityOpsSectionProps({
    summaryState: {
      activityLatestPrimaryReview: derivedState.activityLatestPrimaryReview,
      activityLatestBacktest: derivedState.activityLatestBacktest,
      activityLatestTrackingReview: derivedState.activityLatestTrackingReview,
      activityLatestTrackingJob: derivedState.activityLatestTrackingJob,
      activityLatestBacktestDecisionMeta: derivedState.activityLatestBacktestDecisionMeta,
      activityLatestBacktestWindowMeta: derivedState.activityLatestBacktestWindowMeta,
      activityLatestBacktestReview: derivedState.activityLatestBacktestReview,
      activityLatestBacktestJobMeta: derivedState.activityLatestBacktestJobMeta,
      activityLatestBacktestLineageMeta: derivedState.activityLatestBacktestLineageMeta,
      activityLatestAuditSummary: derivedState.activityLatestAuditSummary,
      activityLatestAlertSummary: derivedState.activityLatestAlertSummary,
      activityLatestOrderSummary: derivedState.activityLatestOrderSummary,
      activityLatestTradeSummary: derivedState.activityLatestTradeSummary,
    },
    topOpsState: {
      activityLatestAlert: derivedState.activityLatestAlert,
      activityLatestPendingAlert: derivedState.activityLatestPendingAlert,
      activityLatestOrder: derivedState.activityLatestOrder,
      activityLatestHistoricalOrder: derivedState.activityLatestHistoricalOrder,
      activityLatestActiveOrder: derivedState.activityLatestActiveOrder,
      activityLatestTrade: derivedState.activityLatestTrade,
      activityLatestActiveOrderEditable: derivedState.activityLatestActiveOrderEditable,
      activityLatestActiveOrderCancellable: derivedState.activityLatestActiveOrderCancellable,
      activityLatestOrderActionLabelPrefix: derivedState.activityLatestOrderActionLabelPrefix,
      activityLatestAuditJobId: derivedState.activityLatestAuditJobId,
      activityLatestAuditLinkedReviewId: derivedState.activityLatestAuditLinkedReviewId,
      activityLatestAuditChangeRequestId: derivedState.activityLatestAuditChangeRequestId,
      activityLatestAuditBacktestId: derivedState.activityLatestAuditBacktestId,
      activityLatestAuditSourceBacktestId: derivedState.activityLatestAuditSourceBacktestId,
      activityLatestAuditSourceReviewId: derivedState.activityLatestAuditSourceReviewId,
      activityLatestAuditSourceProposalId: derivedState.activityLatestAuditSourceProposalId,
      activityLatestAuditStrategyId: derivedState.activityLatestAuditStrategyId,
      activityLatestActiveOrderDiffersFromLatest: derivedState.activityLatestActiveOrderDiffersFromLatest,
      activityLatestActiveOrderSummary: derivedState.activityLatestActiveOrderSummary,
      activityLatestPendingAlertDiffersFromLatest: derivedState.activityLatestPendingAlertDiffersFromLatest,
      activityLatestPendingAlertSummary: derivedState.activityLatestPendingAlertSummary,
      activityLatestActionableProposalDiffersFromLatest: derivedState.activityLatestActionableProposalDiffersFromLatest,
      activityLatestActionableProposalSummary: derivedState.activityLatestActionableProposalSummary,
      activityLatestActionableChangeRequestDiffersFromLatest:
        derivedState.activityLatestActionableChangeRequestDiffersFromLatest,
      activityLatestActionableChangeRequestSummary: derivedState.activityLatestActionableChangeRequestSummary,
      activityLatestRetryableTrackingJobDiffersFromLatest:
        derivedState.activityLatestRetryableTrackingJobDiffersFromLatest,
      activityLatestRetryableTrackingJobSummary: derivedState.activityLatestRetryableTrackingJobSummary,
      activityLatestHistoricalOrderDiffersFromLatest: derivedState.activityLatestHistoricalOrderDiffersFromLatest,
      activityLatestHistoricalOrderSummary: derivedState.activityLatestHistoricalOrderSummary,
      activityLatestActionableBacktestDiffersFromLatest: derivedState.activityLatestActionableBacktestDiffersFromLatest,
      activityLatestActionableBacktestSummary: derivedState.activityLatestActionableBacktestSummary,
      activityLatestActionablePrimaryReviewDiffersFromLatest:
        derivedState.activityLatestActionablePrimaryReviewDiffersFromLatest,
      activityLatestActionablePrimaryReviewSummary: derivedState.activityLatestActionablePrimaryReviewSummary,
    },
    opsState: {
      strategyId: collectionState.strategyId,
      strategyActivityLatestPendingAlertSupplemented: collectionState.strategyActivityLatestPendingAlertSupplemented,
      strategyActivityLatestAlertSupplemented: collectionState.strategyActivityLatestAlertSupplemented,
      strategyActivityAlerts: collectionState.strategyActivityAlerts,
      activityLatestAlert: derivedState.activityLatestAlert,
      activityLatestPendingAlert: derivedState.activityLatestPendingAlert,
      strategyActivityLatestAuditSupplemented: collectionState.strategyActivityLatestAuditSupplemented,
      strategyActivityAuditEvents: collectionState.strategyActivityAuditEvents,
      activityLatestAuditEvent: collectionState.activityLatestAuditEvent,
      strategyActivityLatestActiveOrderSupplemented: collectionState.strategyActivityLatestActiveOrderSupplemented,
      strategyActivityActiveOrders: collectionState.strategyActivityActiveOrders,
      activityLatestActiveOrder: derivedState.activityLatestActiveOrder,
      activityLatestOrder: derivedState.activityLatestOrder,
      strategyActivityLatestHistoricalOrderSupplemented:
        collectionState.strategyActivityLatestHistoricalOrderSupplemented,
      strategyActivityOrders: collectionState.strategyActivityOrders,
      activityLatestHistoricalOrder: derivedState.activityLatestHistoricalOrder,
      strategyActivityLatestTradeSupplemented: collectionState.strategyActivityLatestTradeSupplemented,
      strategyActivityTrades: collectionState.strategyActivityTrades,
      activityLatestTrade: derivedState.activityLatestTrade,
    },
    serviceState: {
      serviceAvailable: serviceState.serviceAvailable,
      selectedMode: serviceState.selectedMode,
      alertMutationPending: serviceState.alertMutationPending,
      cancelPaperOrderPending: serviceState.cancelPaperOrderPending,
      cancelExchangeOrderPending: serviceState.cancelExchangeOrderPending,
    },
    actions: {
      onOpenAlertsSection: actions.onOpenAlertsSection,
      onOpenMarketSymbol: actions.onOpenMarketSymbol,
      onOpenTradesSection: actions.onOpenTradesSection,
      onOpenWatchlistManager: actions.onOpenWatchlistManager,
      onToggleAlertAcknowledged: actions.onToggleAlertAcknowledged,
      onOpenOrderEditor: actions.onOpenOrderEditor,
      onCancelPaperOrder: actions.onCancelPaperOrder,
      onCancelExchangeOrder: actions.onCancelExchangeOrder,
      onOpenAuditSection: actions.onOpenAuditSection,
      onOpenAiSchedulerJob: actions.onOpenAiSchedulerJob,
      onOpenReviewInspector: actions.onOpenReviewInspector,
      onOpenChangeRequest: actions.onOpenChangeRequest,
      onOpenBacktestDetail: actions.onOpenBacktestDetail,
      onOpenSourceReview: actions.onOpenSourceReview,
      onOpenStrategyProposal: actions.onOpenStrategyProposal,
    },
  })
}
