import type {
  BuildAppCompositionModelArgs,
  BuildAppCompositionModelArgsInput,
} from './buildAppCompositionModelArgTypes'
import type { BuildAppCompositionStrategyWorkspaceDerivedStateInputGroups } from './buildAppCompositionStrategyWorkspaceDerivedStateInputGroups'

export function buildAppCompositionStrategyWorkspaceExecutionContextStateArgs(
  input: BuildAppCompositionModelArgsInput,
  pendingStateInput: BuildAppCompositionStrategyWorkspaceDerivedStateInputGroups['pendingStateInput'],
): BuildAppCompositionModelArgs['strategyWorkspaceDerivedStateArgs']['executionContextState'] {
  const {
    selectedStrategy,
    selectedStrategyRuntime,
    latestStrategyBacktest,
    latestStrategyBacktestDecisionMeta,
    latestStrategyBacktestSampleMeta,
    latestStrategyBacktestWindowMeta,
    latestStrategyBacktestLineageMeta,
    latestStrategyBacktestReview,
    latestStrategyBacktestReviewJob,
    latestStrategyBacktestReviewJobMeta,
    selectedStrategyChangeRequest,
    allStrategyChangeRequests,
    strategyChangeRequests,
    strategyProposals,
    backtests,
    proposalBacktestMap,
    proposalReviewMap,
    proposalChangeRequestMap,
    proposalAgentJobMap,
    selectedProposalId,
    selectedChangeRequestId,
    selectedBacktestId,
    reviewInspectorReviewId,
    replayFocusedReviewId,
    aiSchedulerFocusedJobId,
    gatedPublishProposalCount,
    snapshot,
    serviceAvailable,
  } = input

  return {
    selectedStrategy,
    selectedStrategyRuntime,
    latestStrategyBacktest,
    latestStrategyBacktestDecisionMeta,
    latestStrategyBacktestSampleMeta,
    latestStrategyBacktestWindowMeta,
    latestStrategyBacktestLineageMeta,
    latestStrategyBacktestReview,
    latestStrategyBacktestReviewJob,
    latestStrategyBacktestReviewJobMeta,
    selectedStrategyChangeRequest,
    allStrategyChangeRequests,
    strategyChangeRequests,
    strategyProposals,
    backtests,
    proposalBacktestMap,
    proposalReviewMap,
    proposalChangeRequestMap,
    proposalAgentJobMap,
    selectedProposalId,
    selectedChangeRequestId,
    selectedBacktestId,
    reviewInspectorReviewId,
    replayFocusedReviewId,
    aiSchedulerFocusedJobId,
    gatedPublishProposalCount,
    serviceAvailable,
    schedulerState: snapshot?.scheduler ?? null,
    backtestMutationPending: pendingStateInput.strategyWorkflowActions.backtestMutationPending,
    retryAgentJobMutationPending:
      pendingStateInput.strategyWorkflowActions.retryAgentJobMutationPending,
    proposalMutationPending: pendingStateInput.strategyWorkflowActions.proposalMutationPending,
  }
}
