import { useWorkspaceDraftSelectionCleanup } from './useWorkspaceDraftSelectionCleanup'
import { useWorkspaceDraftSyncStrategyEditor } from './useWorkspaceDraftSyncStrategyEditor'
import { useWorkspaceDraftSyncWatchlistAlerts } from './useWorkspaceDraftSyncWatchlistAlerts'
import type { UseWorkspaceDraftSyncArgs } from './useWorkspaceDraftSync.types'

export function useWorkspaceDraftSync({
  selectedStrategy,
  selectedStrategyId,
  selectedStrategyParameterSignature,
  strategyEditorDraftStrategyId,
  strategyEditorOpen,
  setParameterDrafts,
  setRiskBudgetDraft,
  setStrategyEditorDraftStrategyId,
  watchlist,
  watchlistAlertSignature,
  setWatchlistAlertDrafts,
  backtestsForWorkspace,
  selectedBacktestId,
  setSelectedBacktestId,
  selectedProposalId,
  reviewsLoaded,
  proposalCatalog,
  setSelectedProposalId,
  reviewInspectorOpen,
  reviewInspectorReviewId,
  reviewInspectorStrategyId,
  reviewCatalog,
  setReviewInspectorOpen,
  setReviewInspectorReviewId,
  setReviewInspectorStrategyId,
  replayFocusedReviewId,
  setReplayFocusedReviewId,
  aiSchedulerFocusedJobId,
  schedulerLoaded,
  schedulerJobs,
  setAiSchedulerFocusedJobId,
  selectedChangeRequestId,
  changeRequestsLoaded,
  changeRequests,
  setSelectedChangeRequestId,
  editingOrderId,
  editingOrder,
  setEditingOrderId,
  setManualTradePanelOpen,
}: UseWorkspaceDraftSyncArgs) {
  useWorkspaceDraftSyncStrategyEditor({
    selectedStrategyParameters: selectedStrategy?.parameters ?? [],
    selectedStrategyRiskBudget: selectedStrategy?.risk_budget ?? '',
    selectedStrategyId,
    selectedStrategyParameterSignature,
    strategyEditorDraftStrategyId,
    strategyEditorOpen,
    setParameterDrafts,
    setRiskBudgetDraft,
    setStrategyEditorDraftStrategyId,
  })

  useWorkspaceDraftSyncWatchlistAlerts({
    watchlist,
    watchlistAlertSignature,
    setWatchlistAlertDrafts,
  })

  useWorkspaceDraftSelectionCleanup({
    backtestsForWorkspace,
    selectedBacktestId,
    setSelectedBacktestId,
    selectedProposalId,
    reviewsLoaded,
    proposalCatalog,
    setSelectedProposalId,
    reviewInspectorOpen,
    reviewInspectorReviewId,
    reviewInspectorStrategyId,
    reviewCatalog,
    setReviewInspectorOpen,
    setReviewInspectorReviewId,
    setReviewInspectorStrategyId,
    replayFocusedReviewId,
    setReplayFocusedReviewId,
    aiSchedulerFocusedJobId,
    schedulerLoaded,
    schedulerJobs,
    setAiSchedulerFocusedJobId,
    selectedChangeRequestId,
    changeRequestsLoaded,
    changeRequests,
    setSelectedChangeRequestId,
    editingOrderId,
    editingOrder,
    setEditingOrderId,
    setManualTradePanelOpen,
  })
}
